### ISSUE TITLE
Cannot switch between variations, always brought back to current variation

### ISSUE THREAD

**Issue by emiliegervais** [yoriiis/abtasty-debugger#32]
### Describe the bug

Clicking on a different variation than current variation does not change the variation after page reload. We're brought back into AB Tasty's variation set for us.

Per example, in the below screenshot, I should end up on the original version on page reload, I am not. I am back onto the variation 1. 

![Capture d’écran 2024-06-13 à 18 09 14](https://github.com/yoriiis/abtasty-debugger/assets/4047984/6802b5ee-3b26-496e-8458-ee76b023d7b5)

### Steps to reproduce

1. Enable extension
2. Have an AB test available with different variations 
3. Click on a different variation
4. Close extension or check in the page which variation you're seeing
5. Reopen extension

### Expected behavior

I should see the variation I wanna see on page reload.

### AB Tasty Debugger

the last one

### Browser

ARC (Chrome)

### OS

macOs 14.4.1

**Comment by yoriiis** [comment]
@emiliegervais The fix is merged and will be available in the next release soon on Chrome, Edge and Firefox
